### ISSUE TITLE
Unclosed tags (LinkedIn)

### ISSUE THREAD

**Issue by hwahyeon** [pirjademl/pirjademl.github.io#5]
Hello!

The footer displays multiple LinkedIn icons due to unclosed icon tags.

![link](https://github.com/pirjademl/pirjademl.github.io/assets/46473089/d4dddd46-79da-4704-9a70-5c32eb3feb4b)

Current issue:
```javascript
<a href="https://www.linkedin.com"><i class="fa-brands fa-linkedin-in">
```

Suggested fix:
```javascript
<a href="https://www.linkedin.com"><i class="fa-brands fa-linkedin-in"></i></a>
```

**Comment by pirjademl** [comment]
thanks for pointing out the mistake I'll fix it , 
if you want to do it you can do it otherwise i'll do  it

**Comment by hwahyeon** [comment]
@pirjademl 
Thanks for the offer, but it seems best if you fix it : )
